In [2]:
#根据正则化，实现岭回归模型
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#读入数据
data = np.genfromtxt("longley.csv", delimiter=',')
#切分数据
x_data = data[1:, 2:]
#这里要y_data增加维度
y_data = data[1:, 1, np.newaxis]
print(x_data)
print(y_data)

[[ 234.289  235.6    159.     107.608 1947.      60.323]
 [ 259.426  232.5    145.6    108.632 1948.      61.122]
 [ 258.054  368.2    161.6    109.773 1949.      60.171]
 [ 284.599  335.1    165.     110.929 1950.      61.187]
 [ 328.975  209.9    309.9    112.075 1951.      63.221]
 [ 346.999  193.2    359.4    113.27  1952.      63.639]
 [ 365.385  187.     354.7    115.094 1953.      64.989]
 [ 363.112  357.8    335.     116.219 1954.      63.761]
 [ 397.469  290.4    304.8    117.388 1955.      66.019]
 [ 419.18   282.2    285.7    118.734 1956.      67.857]
 [ 442.769  293.6    279.8    120.445 1957.      68.169]
 [ 444.546  468.1    263.7    121.95  1958.      66.513]
 [ 482.704  381.3    255.2    123.366 1959.      68.655]
 [ 502.601  393.1    251.4    125.368 1960.      69.564]
 [ 518.173  480.6    257.2    127.852 1961.      69.331]
 [ 554.894  400.7    282.7    130.081 1962.      70.551]]
[[ 83. ]
 [ 88.5]
 [ 88.2]
 [ 89.5]
 [ 96.2]
 [ 98.1]
 [ 99. ]
 [100. ]
 [101.2]
 [104.

In [4]:
print(np.mat(x_data).shape)
print(np.mat(y_data).shape)
#加入偏置，将b吸入向量形式
print(np.ones((16, 1)))  # 16行1列的全1.矩阵
# np.concatenate((np.ones((16,1)), np.zeros((16,2))),axis=1)    # 演示np.concatenate的用法
X_data = np.concatenate((np.ones((16, 1)), x_data), axis=1)
X_data

(16, 6)
(16, 1)
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


array([[1.00000e+00, 2.34289e+02, 2.35600e+02, 1.59000e+02, 1.07608e+02,
        1.94700e+03, 6.03230e+01],
       [1.00000e+00, 2.59426e+02, 2.32500e+02, 1.45600e+02, 1.08632e+02,
        1.94800e+03, 6.11220e+01],
       [1.00000e+00, 2.58054e+02, 3.68200e+02, 1.61600e+02, 1.09773e+02,
        1.94900e+03, 6.01710e+01],
       [1.00000e+00, 2.84599e+02, 3.35100e+02, 1.65000e+02, 1.10929e+02,
        1.95000e+03, 6.11870e+01],
       [1.00000e+00, 3.28975e+02, 2.09900e+02, 3.09900e+02, 1.12075e+02,
        1.95100e+03, 6.32210e+01],
       [1.00000e+00, 3.46999e+02, 1.93200e+02, 3.59400e+02, 1.13270e+02,
        1.95200e+03, 6.36390e+01],
       [1.00000e+00, 3.65385e+02, 1.87000e+02, 3.54700e+02, 1.15094e+02,
        1.95300e+03, 6.49890e+01],
       [1.00000e+00, 3.63112e+02, 3.57800e+02, 3.35000e+02, 1.16219e+02,
        1.95400e+03, 6.37610e+01],
       [1.00000e+00, 3.97469e+02, 2.90400e+02, 3.04800e+02, 1.17388e+02,
        1.95500e+03, 6.60190e+01],
       [1.00000e+00, 4.19180

In [6]:
# 岭回归标准方程法求参数
def weights(xArr, yArr, lam):
    xMat = np.mat(xArr)
    yMat = np.mat(yArr)
    xTx = xMat.T * xMat  # 矩阵乘法
    rxTx = xTx + lam*np.eye(xMat.shape[1])  # 生成7行7列的单位矩阵
    if np.linalg.det(rxTx) == 0.0:  # 如果矩阵值为零，就结束
        print("This matrix cannot do inverse")
        return
    # 求逆
    w = rxTx.I * xMat.T * yMat
    return w

In [9]:
w = weights(X_data,y_data,0.2)
print(w)  # 得到7个系数

[[ 7.38106779e-04]
 [ 2.07703836e-01]
 [ 2.10076376e-02]
 [ 5.05385441e-03]
 [-1.59173066e+00]
 [ 1.10442920e-01]
 [-2.42280461e-01]]


In [10]:
# 预测结果
np.mat(X_data) * np.mat(w)

matrix([[ 83.55075226],
        [ 86.92588689],
        [ 88.09720227],
        [ 90.95677622],
        [ 96.06951002],
        [ 97.81955375],
        [ 98.36444357],
        [ 99.99814266],
        [103.26832266],
        [105.03165135],
        [107.45224671],
        [109.52190685],
        [112.91863666],
        [113.98357055],
        [115.29845063],
        [117.64279933]])